### ISSUE TITLE
error

### ISSUE THREAD

**Issue by XDqrkneZ** [CosmoSunriseServerPluginEditorsTeam/MoneySAPI#1]
20:59:32 [INFO] Enabling MoneySAPI v2.3.1
> org.sqlite.JDBC
No suitable driver found for jdbc:sqlite:C:\Users\arjxy\Desktop\nukkit server\plugins\MoneySAPI/DataDB.db
20:59:32 [ALERT] java.lang.RuntimeException: java.lang.NoClassDefFoundError: itsu/mcbe/form/element/Button
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439)
        at cn.nukkit.Server.enablePlugin(Server.java:670)
        at cn.nukkit.Server.enablePlugins(Server.java:659)
        at cn.nukkit.Server.<init>(Server.java:503)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NoClassDefFoundError: itsu/mcbe/form/element/Button
        at net.comorevi.moneyapi.MoneySAPI.onEnable(MoneySAPI.java:140)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:435)
        ... 4 more
Caused by: java.lang.ClassNotFoundException: itsu.mcbe.form.element.Button
        at java.net.URLClassLoader.findClass(Unknown Source)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more

20:59:32 [INFO] Disabling MoneySAPI v2.3.1

**Comment by popkechupki** [comment]
I am sorry for the delay in my reply.
If you want to use this, you have to use NukkitFormAPI along with this plugin.
